config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated  do
    root "base#index", as: 'unauthenticated_user'
  end
  unauthenticated do
    root "base#about"
  end

  get "about", to: "base#about"
  get "welcome", to: "base#welcome"
  post "offline_data", to: "base#update_offline_data"

  get "events/drag", to: "events#drag"
  post "events/search", to: "events#search"
  post "eventrestore", to: "event_versions#restore", as: "eventrestore"
  get "event_versions/compare", to: "event_versions#compare"

  post "contactrestore", to: "contact_versions#restore", as: "contactrestore"
  post "contacts/search", to: "contacts#search"
  get "contact_versions/compare", to: "contact_versions#compare"

  post "postrestore", to: "post_versions#restore", as: "postrestore"
  post "posts/search", to: "posts#search"
  delete "post/image", to: "posts#destroy_image"
  get "post_versions/compare", to: "post_versions#compare"

  post "passkeyrestore", to: "passkey_versions#restore", as: "passkeyrestore"
  post "passkeys/search", to: "passkeys#search"
  get "passkeys/:id/password", to: "passkeys#password", as: "passkey_password"
  get "passkey_versions/compare", to: "passkey_versions#compare"

  resources :events
  resources :event_versions
  resources :contacts
  resources :contact_versions
  resources :posts
  resources :post_versions
  resources :passkeys
  resources :passkey_versions
  resources :passkey_shares

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  def index
    @user = User.find current_user.id
    @events = Event.where("(start >= ? AND start <= ?) OR (end >= ? AND end <= ?)",
     Date.today, Date.today + 14.day, Date.today, Date.today + 14.day)
      .where(user_id: current_user.id).order(start: :asc)
  end

  def update_offline_data
    current_user.update(offline_data: params[:offline_data] == 'true')
    render json: { offline_data: current_user.offline_data }
  end

end

app/views/base/_resource_footer.html.erb
<div class="row">
  <div class="columns"><label class="label-th"></label></div>
  <div class="columns small-6 medium-6 meta-data">Created: <%= l resource.created_at, format: :default if resource.created_at %></div>
  <div class="columns small-6 medium-6 meta-data">Updated: <%= l resource.updated_at, format: :default if resource.updated_at %></div>
</div>

app/views/base/about.erb
<div class="row">
  <div class="columns small-12 medium-8">
    <h1 class="home">PIM</h1><span>Personal Information Manager</span>
  </div>
  <%= content_tag :div, class: "columns small-12 medium-4 text-right p-4" do %>
    <%= link_to "Log in", new_user_session_path, class: "button" %>
    <%= link_to "Sign up", new_user_registration_path, class: "button notice" %>
  <% end unless current_user %>
</div>
<div class="row">
  <div class="column small-12 start p-4" id="start">
    <p class="radius">Keep your personal information private</p>
    <%= link_to "Calendar", events_path, class: "button" %>
    <%= link_to "Contacts", contacts_path, class: "button" %>
    <%= link_to "Notes", posts_path, class: "button" %>
    <%= link_to "Keys", passkeys_path, class: "button" %>
  </div>
</div>
<div class="row">
  <div class="column small-12">
    <h2 class="fi-lock"> Access to your data</h2>
    <p>Access your data wherever you are, whenever you need it, all under your control.</p>
  </div>
</div>
<div class="row">
  <div class="column small-12 medium-6">
    <h2> Pros</h2>
    <p>
    Independent of Google, iCloud, Facebook or other installed app/provider who can peek into your data.
    Contact data is not linked to native addressbook, calendar or notes.
    Its is a very fast and lightweight app unlike Nextcloud.
    You can install this service on you own server or use&nbsp;<a href="https://pim.filmer.nl">pim.filmer.nl</a>.
    </p>
  </div>
  <div class="column small-12 medium-6">
    <h2> Cons</h2>
    <p>
    This web-app is not installed and therefore not link to incomming calls on your smartphone.</p>
  </div>
</div>
<div class="row">
  <div class="column small-12">
    <h2> General features</h2>
    <ul>
      <li>This 'Web App' has a responsive design so you can use it on your mobile, tablet or desktop.</li>
      <li>All main items has interactive searches.</li>
      <li><a href="http://showdownjs.github.io/demo/" target="_blank">Markdown is integrated.</a>so you can style your text easily.</li>
      <li>Revisions, all information is stored with revisions and can be viewed and restored.</i></li>
      <li>When offline mode (default off) is enabled <strong>the data is unencrypted</strong> in IndexedDB!
      <li>Open source and the code has <a href="http://opensource.org/licenses/MIT" target="_blank">MIT License</a>,
        see full source code on <a href="https://github.com/andriesfilmer/pim" target="_blank"> Github.</a></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="column small-12">
    <h2> Calendar</h2>
    <ul>
      <li>The calendar has month, day and list view.</li>
      <li>Calendar is timezone aware.</li>
      <li>Get reminders by e-mail (crontab script included).</li>
    </ul>
    <h2> Contacts</h2>
    <ul>
      <li>Create contacts and add unlimited phonenumbers, companies, relations, e-mailaddresses, websites, addresses.</li>
      <li>There is a starred, birthdates and list view.</li>
      <li>Add a birthdate to a contact and get a reminder by e-mail.</li>
    </ul>
    <h2> Notes</h2>
    <ul>
      <li>Make a small note, todo or a big article with Markdown.</li>
      <li>Auto-generate a table of contents (TOC) on a large articles.</li>
    </ul>
    <h2> Keys</h2>
    <ul>
      <li>Use this pim as you password manager.</li>
      <li>Username, password en notes wil be encrypted in the database.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="column small-12 medium-12">
    <h2> Install this web app</h2>
    <p>If you want a icon on your tablet or smartphone homescreen like a real App.</p>
  </div>
</div>

app/views/base/index.erb
<div class="row">
  <div class="columns small-8 medium-10">
    <h1 class="home">PIM</h1>
    <div id="installButton" class="button filter-diap icon sm install-mobile display-none">Install App</div>
  </div>
  <div class="columns small-4 medium-2 text-right p-4">
    <%= link_to "Edit profile", edit_user_registration_path, class: "button small" %>
  </div>
</div>
<div class="row p-4" data-controller="user">
  <div class="columns medium-6">
    <div class="home meta-data">Personal Information Manager</div>
    <%= content_tag :div, @user.name %>
  </div>
  <div class="columns small-4 medium-2 p-4">
    <label>Light mode</label>
    <%= label_tag "theme_light", class: "switch" do %>
      <%= radio_button_tag "theme", "light", nil, data: { action: "click->user#setTheme" }, class: "switch" %>
      <span class="slider round"></span>
    <% end %>
  </div>
  <div class="columns small-4  medium-2 p-4">
    <label>Dark mode</label>
    <%= label_tag "theme_dark", class: "switch" do %>
      <%= radio_button_tag "theme", "dark", nil, data: { action: "click->user#setTheme" }, class: "switch" %>
      <span class="slider round"></span>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="columns">
    <h2 class="icon event-note"> Upcomming events </h3>
  </div>
</div>
<%= render "events/events" %>