config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated  do
    root "base#index", as: 'unauthenticated_user'
  end
  unauthenticated do
    root "base#about"
  end

  get "about", to: "base#about"
  get "welcome", to: "base#welcome"
  post "offline_data", to: "base#update_offline_data"

  get "events/drag", to: "events#drag"
  post "events/search", to: "events#search"
  post "eventrestore", to: "event_versions#restore", as: "eventrestore"
  get "event_versions/compare", to: "event_versions#compare"

  post "contactrestore", to: "contact_versions#restore", as: "contactrestore"
  post "contacts/search", to: "contacts#search"
  get "contact_versions/compare", to: "contact_versions#compare"

  post "postrestore", to: "post_versions#restore", as: "postrestore"
  post "posts/search", to: "posts#search"
  delete "post/image", to: "posts#destroy_image"
  get "post_versions/compare", to: "post_versions#compare"

  post "passkeyrestore", to: "passkey_versions#restore", as: "passkeyrestore"
  post "passkeys/search", to: "passkeys#search"
  get "passkeys/:id/password", to: "passkeys#password", as: "passkey_password"
  get "passkey_versions/compare", to: "passkey_versions#compare"

  resources :events
  resources :event_versions
  resources :contacts
  resources :contact_versions
  resources :posts
  resources :post_versions
  resources :passkeys
  resources :passkey_versions
  resources :passkey_shares

end

app/models/event.rb
class Event < ApplicationRecord

  alias_attribute :start_date, :start
  alias_attribute :start_time, :start
  alias_attribute :end_date, :end
  alias_attribute :end_time, :end
  alias_attribute :notes, :description
  alias_attribute :category, :className
  alias_attribute :created_at, :created
  alias_attribute :updated_at, :updated

  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true

  #after_find :get_offset_time
  #before_save :set_offset_time

  private

  def self.set_start(start_date,start_time)
    "#{start_date} #{start_time}"
  end

  def self.set_end(end_date,end_time)
    "#{end_date} #{end_time}"
  end

  def get_offset_time
    self.start = self.start.to_datetime.in_time_zone(self.tz).to_s[0,16]
    self.end = self.end.to_datetime.in_time_zone(self.tz).to_s[0,16]
  end

  def set_offset_time
    self.start = self.start.to_datetime.in_time_zone(self.tz).to_s[0,16]
    self.end = self.end.to_datetime.in_time_zone(self.tz).to_s[0,16]
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = if params[:start] && params[:end]
                # Needs session id to implement.
                Event.where('user_id=?', current_user.id)
                     .where('start < ?', params[:end][0..9])
                     .where('end > ?', params[:start][0..9]).limit 500
              else
                Event.where(user_id: current_user.id).order('id desc').limit 500
              end
    respond_to do |format|
      format.html
      format.json do
        events_data = @events.map do |event|
          event_hash = event.as_json
          if event.allDay == 1
            event_hash['end'] = (event.end + 24.hours)
          end
          event_hash
        end
        render json: events_data
      end
    end
  end

  def new
    event_start = params[:start].present? ? params[:start].to_date : Date.today
    event_end   = params[:end].present?   ? params[:end].to_date : Date.today
    @event = Event.new(start: event_start, end: event_end.end_of_day.to_s[0, 16])
  end

  def show
    # @event.update(last_read: DateTime.now)

    redirect_to events_path, alert: 'Event does not exists (anymore)' unless @event

    respond_to do |format|
      format.html
      format.json { render json: @event.to_json } # else only id, created_at, updated_at
    end
  end

  def create
    Time.zone = params[:event][:tz]
    format_event_dates
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to events_path(date: @event.start.strftime('%Y-%m-%d')), notice: 'Event was successfully created.'
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('eventForm', partial: 'events/form', locals: { resource: @event })
        end
      end

      # Create a copy for versions management.
      add_version(@event) if @event.errors.empty?
    end
  end

  def update
    Time.zone = params[:event][:tz]
    format_event_dates

    respond_to do |format|
      if @event.update(event_params)
        flash.now[:notice] = 'Event was successfully updated.'
        format.html do
          redirect_to events_path(date: @event.start.strftime('%Y-%m-%d')), notice: 'Event was successfully updated.'
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('eventForm', partial: 'events/form', locals: { resource: @event })
        end
      end
    end

    # Create a copy for versions management.
    return unless @event.errors.empty?

    add_version(@event)
  end

  def destroy
    @event.destroy
    respond_to do |format|
      # format.turbo_stream { flash.now[:notice] = "Turbo event was successfully deleted." }
      format.html { redirect_to events_path, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].length > 2
      search = "%#{params[:search]}%"
      @events = Event.where('title LIKE ? OR description LIKE ? OR tags LIKE ?', search, search, search)
                     .order(start: :desc).where(user_id: current_user.id)
      cookies[:search] = { value: params[:search], expires: 1.hour, httponly: true, secure: Rails.env.production? }
    else
      @events = []
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('calendar', partial: 'events', locals: { events: @events })
        ]
      end
    end
  end

  private

  def format_event_dates
    params[:event][:start] = "#{params[:event][:start_date]}  #{params[:event][:start_time]}"
    params[:event][:end] = "#{params[:event][:end_date]}  #{params[:event][:end_time]}"
  end

  def add_version(event)
    # Create a copy for versions management.
    @event_version = EventVersion.new(event_params.except('id', 'mongo_id', 'created_at', 'updated_at', 'start_date',
                                                          'start_time', 'end_date', 'end_time'))
    @event_version.org_id = event.id
    @event_version.user_id = current_user.id
    @event_version.save
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    # Fetch timezone first and set it before loading the full event
    event_tz = Event.where(user_id: current_user.id).where(id: params[:id]).pluck(:tz).first
    redirect_to events_path, alert: 'Event does not exists (anymore)' and return if event_tz.blank?

    Time.zone = event_tz

    @event = Event.where(user_id: current_user.id).where(id: params[:id]).take
    redirect_to events_path, alert: 'Event does not exists (anymore)' and return if @event.blank?

  end

  def event_params
    params.require(:event).permit(:title, :notes, :start, :end, :allDay, :tz, :category, :tags)
  end
end

app/views/events/_events.html.erb
<div id="events" class="col-12" data-turbo-prefetch="false">
<% @events.each do |event| %>
  <% Time.zone = event.tz %>
  <%= link_to event_path(event), class: "row odd p-2 #{event.category}" do %>
  <div class="small-12 medium-8 columns">
    <%= event.title %>
  </div>
  <div class="small-8 medium-3 columns">
    <%= content_tag :label, l(event.start, format: :longnotime) %>
  </div>
  <div class="small-4 medium-1 columns text-center">
    <%= content_tag :label, (event.allDay? ? "Allday" : l(event.start, format: :short)),
     class: event.allDay? ? "button tiny" : "" %>
  </div>
  <% end %>
<% end %>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event, id: "eventForm", class: "userinputs" do |form| %>
  <%= render "layouts/show_errors", resource: @event %>
  <div class="row">
    <div class="columns">
      <%= form.text_field :title, placeholder: "Title of event"%>
    </div>
  </div>

  <div class="row display-none" id="tz">
    <div class="columns small-4 medium-2 tz-warning">Timezone</div>
    <div class="columns small-8 medium-10">
      <%= form.select(:tz, ActiveSupport::TimeZone.all.collect {|tz| ["(GMT#{ActiveSupport::TimeZone.seconds_to_utc_offset(tz.utc_offset)}) #{tz.name}", tz.tzinfo.name]},
          { selected: @event.tz, prompt: '' }, { id: 'event_tz' }) %>
    </div>
  </div>

  <!-- date -->
  <div class="row">
    <div class="columns small-2 medium-2">Start</div>
    <div class="columns small-5 medium-6"><%= form.date_field :start_date, id: 'event_start_date', data: { action: "event#changeDatetime" } %></div>
    <div class="columns small-5 medium-4">
      <%= form.time_field :start_time, id: 'event_start_time', data: { action: "event#changeDatetime" }, class: ("display-none" if truthy? @event.allDay) %>
    </div>
  </div>
  <div class="row">
    <div class="columns small-2 medium-2">End</div>
    <div class="columns small-5 medium-6"><%= form.date_field :end_date, id: 'event_end_date', data: { action: "event#changeDatetime" } %></div>
    <div class="columns small-5 medium-4">
      <%= form.time_field :end_time, id: 'event_end_time', data: { action: "event#changeDatetime" }, class: ("display-none" if truthy? @event.allDay) %>
    </div>
  </div>
  <div class="row pb-4">
    <div class="columns small-2 medium-2">Allday</div>
    <div class="columns small-10 medium-10">
      <%= form.label :allDay, class: "switch" do %>
        <%= form.check_box :allDay, id: 'event_allDay', checked: (truthy? @event.allDay), class: "switch-paddle", data: { action: "click->event#toggleAllDay" } %>
        <span class="slider round"></span>
      <% end %>
    </div>
  </div>

  <!-- notes -->
  <div class="row">
    <div class="columns">
      <%= form.label :notes, class: "display-inline text-lg" %>
      <div class="icon markdown align-bottom" id="preview_bt" data-action="click->event#showMarkdown" data-tooltip title="Click to see markdown format"></div>
      <div class="icon edit align-bottom display-none" id="edit_bt" data-action="click->event#hideMarkdown" data-tooltip title="Click to edit"></div>
      <%= form.text_area :notes, id: 'event_notes', placeholder: 'You can use markdown for notes', rows: '10' %>
      <div id="markdown"></div>
    </div>
  </div>

  <div class="row">
    <div class="medium-6 columns">
    <fieldset>
      <legend class="strong">Category</legend>
      <div class="row p-4">
        <div class="column small-6 medium-6">Appointment</div>
        <div class="column small-6 medium-6 appointment">
        <%= form.label :category_appointment, class: "switch" do %>
          <%= form.radio_button :category, "appointment", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Memo</div>
        <div class="column small-6 medium-6 memo">
        <%= form.label :category_memo, class: "switch" do %>
          <%= form.radio_button :category, "memo", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Task</div>
        <div class="column small-6 medium-6 task">
        <%= form.label :category_task, class: "switch" do %>
          <%= form.radio_button :category, "task", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Business</div>
        <div class="column small-6 medium-6 business">
        <%= form.label :category_business, class: "switch" do %>
          <%= form.radio_button :category, "business", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Holiday</div>
        <div class="column small-6 medium-6 holiday">
        <%= form.label :category_holiday, class: "switch" do %>
          <%= form.radio_button :category, "holiday", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
    </fieldset>
    </div>
    <div class="columns medium-6">
    <fieldset>
      <legend class="strong">Tags</legend>
      <%= form.text_field :tags, id: 'event_tags', placeholder: 'Comma separeted values' %>
      <div id="tagsContainer"></div>
    </fieldset>
    </div>
  </div>
<% end %>
<%= render "base/resource_footer", resource: @event %>

app/views/events/_restore_menu.html.erb
<div class="row hide-for-print">
  <div class="columns medium-6" id="add-back-arrow">
    <h1 class="icon arrow-back cursor-pointer"></h1>
  </div>
  <div class="columns medium-6 text-right">
    <p><%= button_to "Restore version #{@event.id}", eventrestore_path,
      params: { version_id: @event.id} , class: "button warning" if @event.id %></p>
  </div>
</div>

app/views/events/_secondary_menu.html.erb
<div class="row mb-6 hide-for-print">
  <div class="columns small-9 medium-9">
    <%= content_tag :div, '', class: "icon event-note p-2 cursor-pointer border-right-dashed" unless @event.id %>

    <%= link_to (content_tag :div, '', class: "icon event-note p-2 border-right-dashed"),
      event_path(@event), title: "Back to event without saving" if @event.id %>

    <%= link_to (content_tag :div, '', class: "icon edit p-2 border-right-dashed"), edit_event_path(@event), title: "Edit event" if action_name == "show"%>

    <%= content_tag :div, '', class: "icon cloud-upload p-2 cursor-pointer border-right-dashed", id: "cloud-upload",
      data: { action: "click->event#submitForm" },  title: "Save event" if action_name != "show" %>

    <%= link_to (content_tag :div, '', class: "icon restore p-2 border-right-dashed"),
      event_versions_path(org_id: @event.id), title: "Versions of this event" if @event.id %>

    <%= content_tag :div, '', class: "icon more-time cursor-pointer p-2", data: { action: "click->event#showTimezones" },
       title: "Toggle timezones" if action_name != "show" %>

  </div>
  <div class="columns small-3 medium-3 text-right">
    <%= link_to (content_tag :div, '', class: "icon delete pt-2"), event_path(@event),
      data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete this event?'} if @event.id %>
  </div>
</div>

app/views/events/edit.html.erb
<div data-controller="event">
  <%= render "secondary_menu" %>
  <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<div class="row hide-for-print" data-controller="event">
  <div class="small-10 medium-10 columns">
    <div class="icon calendar-month p-2 cursor-pointer border-right-dashed" title="Month grid" data-action="click->event#showMonthView"></div>
    <div class="icon calendar-view-week p-2 cursor-pointer border-right-dashed" title="Week grid" data-action="click->event#showWeekView"></div>
    <div class="icon list p-2 cursor-pointer border-right-dashed" title="List events" data-action="click->event#showListMonth"></div>
    <div class="icon search p-2 cursor-pointer" data-action="click->event#showSearch" title="Search events"></div>
  </div>
  <div class="small-2 medium-2 columns p-2 text-right">
    <%= link_to (content_tag :div, '', class: "icon add"), new_event_path, title: "Add event" %>
  </div>
</div>

<div id="show_search" class="row display-none">
  <div class="columns">
  <%= form_with url: events_search_path, id: "search-form" do |form| %>
    <%= form.search_field :search, id: 'search', placeholder: 'Search events', value: cookies[:search],
      data: { controller: "event", action: "focus->event#search input->event#search" } %>
  <% end %>
  </div>
</div>

<div class="row pt-4">
  <div class="columns" id="calendar"></div>
</div>

app/views/events/new.html.erb
<div data-controller="event">
  <%= render "secondary_menu" %>
  <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<%= render "events/secondary_menu" unless @event.try(:org_id) %>
<%= render "events/restore_menu" if @event.try(:org_id) %>

<%= form_with model: @event do |form| %>

<div class="row">
  <div class="columns <%= @event.category %>">
    <h2 class="th"><%= @event.title %></h2>
  </div>
</div>

<div class="row">
  <div class="columns tz-warning display-none">Created or edited in different timezone!</div>
  <div class="columns display-inline">
    <%= content_tag :label, @event.tz, class: "button small tz-show display-none mr-2" %>
    <%= content_tag :label, l(@event.start, format: :mediumnotime), class: "button small mr-2" if @event.allDay  == 1 %>
    <%= content_tag :label, l(@event.start, format: :medium), class: "button small mr-2" unless @event.allDay == 1 %>
    <%= content_tag :label, l(@event.end, format: :mediumnotime), class: "button small mr-2" if @event.allDay == 1 %>
    <%= content_tag :label, l(@event.end, format: :medium), class: "button small mr-2" unless @event.allDay == 1 %>
    <%= content_tag :label, "Allday", class: "button small" if @event.allDay == 1 %>
  </div>
  <div class="columns tz-warning display-none pt-3">Browser timezone</div>
  <div class="columns tz-warning display-none">
    <%= content_tag :label, "", id: "tzBrowser", class: "button small mr-2" %>
    <%= content_tag :label, "", id: "browserEventStart", class: "button small mr-2" %>
    <%= content_tag :label, "", id: "browserEventEnd", class: "button small" %>
  </div>
</div>

<div class="row">
  <div class="columns">
    <%= content_tag :pre, @event.notes, id: "notes", class: "display-none" %>
    <div data-controller="event" id="markdown"></div>
  </div>
</div>

<div class="row hide-for-print">
  <div class="columns">
    <%= content_tag :div, '', id: "tagsContainer" if @event.tags.present? %>
    <%= form.hidden_field :tags %>
  </div>
</div>

  <%= form.hidden_field :tz, id: 'event_tz' %>
  <%= form.hidden_field :start, id: 'event_start' %>
  <%= form.hidden_field :end, id: 'event_end' %>

<% end %>

<%= render "base/resource_footer", resource: @event %>