config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated  do
    root "base#index", as: 'unauthenticated_user'
  end
  unauthenticated do
    root "base#about"
  end

  get "about", to: "base#about"
  get "welcome", to: "base#welcome"
  post "offline_data", to: "base#update_offline_data"

  get "events/drag", to: "events#drag"
  post "events/search", to: "events#search"
  post "eventrestore", to: "event_versions#restore", as: "eventrestore"
  get "event_versions/compare", to: "event_versions#compare"

  post "contactrestore", to: "contact_versions#restore", as: "contactrestore"
  post "contacts/search", to: "contacts#search"
  get "contact_versions/compare", to: "contact_versions#compare"

  post "postrestore", to: "post_versions#restore", as: "postrestore"
  post "posts/search", to: "posts#search"
  delete "post/image", to: "posts#destroy_image"
  get "post_versions/compare", to: "post_versions#compare"

  post "passkeyrestore", to: "passkey_versions#restore", as: "passkeyrestore"
  post "passkeys/search", to: "passkeys#search"
  get "passkeys/:id/password", to: "passkeys#password", as: "passkey_password"
  get "passkey_versions/compare", to: "passkey_versions#compare"

  resources :events
  resources :event_versions
  resources :contacts
  resources :contact_versions
  resources :posts
  resources :post_versions
  resources :passkeys
  resources :passkey_versions
  resources :passkey_shares

end

app/models/passkey.rb
class Passkey < ApplicationRecord
  # https://guides.rubyonrails.org/active_record_encryption.html
  encrypts :username # , previous: { deterministic: true }
  encrypts :password
  encrypts :notes, deterministic: true # , previous: { deterministic: false }

  has_many :passkey_shares, dependent: :destroy

  validates :title, presence: true

  def self.encrypt_passkeys
    passkeys = Passkey.all
    passkeys.each do |passkey|
      passkey.encrypt
    end
  end

  def self.decrypt_passkeys
    # Needed in the config you're using (production.rb, development.rb)
    # config.active_record.encryption.support_unencrypted_data = true
    passkeys = Passkey.all
    passkeys.each do |passkey|
      passkey.decrypt
    end
  end
end

app/controllers/passkeys_controller.rb
class PasskeysController < ApplicationController
  before_action :set_passkey, only: %i[edit update]

  def index
    @passkeys = Passkey.left_joins(:passkey_shares)
                       .where("(passkeys.user_id = ?) OR (passkey_shares.linked_user_id = ?)", current_user.id, current_user.id)
                       .order(last_read: :desc).limit(500)

    respond_to do |format|
      format.html
      format.json { render json: @passkeys }
    end
  end

  def show
    @passkey = Passkey.left_joins(:passkey_shares).select('passkeys.*,passkey_shares.user_id AS shared_by_user_id')
                      .where("(passkeys.user_id = ? AND passkeys.id = ?) OR (passkey_shares.passkey_id = ? AND passkey_shares.linked_user_id = ?)",
                             current_user.id, params[:id], params[:id], current_user.id).take

    redirect_to passkeys_url, alert: 'Key not found.' and return if @passkey.blank?

    # Don't show edit, update and share items in show if it's a shared key
    @passkey_readonly = !(@passkey.user_id == current_user.id)

    @passkey.update_column(:last_read, DateTime.now)

    # Needed for form @passkey_share to add new shares.
    @passkey_share = PasskeyShare.new(passkey_id: @passkey.id) if @passkey.id

    return if @passkey_readonly

    @passkey_shares = PasskeyShare.where(passkey_id: @passkey.id).where(user_id: current_user.id)
  end

  def new
    @passkey = Passkey.new
    @passkey_share = PasskeyShare.new
    @passkey_shares = PasskeyShare.where(passkey_id: @passkey.id).where(user_id: current_user.id)
  end

  def edit
    @passkey_share = PasskeyShare.new(passkey_id: @passkey.id)
    @passkey_shares = PasskeyShare.where(passkey_id: @passkey.id).where(user_id: current_user.id)
  end

  def create
    @passkey = Passkey.new(passkey_params)
    @passkey.user_id = current_user.id

    respond_to do |format|
      if @passkey.save
        format.html { redirect_to passkey_url(@passkey), notice: 'Key was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('passkeyForm', partial: 'passkeys/form', locals: { resource: @passkey })
        end
      end
    end

    # Create a copy for versions management.
    add_version(@passkey)
  end

  def update
    respond_to do |format|
      if @passkey.update(passkey_params)
        format.html { redirect_to passkey_url(@passkey), notice: 'Key was successfully updated.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('passkeyForm', partial: 'passkeys/form', locals: { resource: @passkey })
        end
      end
    end

    # Create a copy for versions management.
    add_version(@passkey)
  end

  def destroy
    passkey = if params[:shared_by_user_id].present?
                PasskeyShare.where(passkey_id: params[:id]).where(linked_user_id: current_user.id).take
              else
                Passkey.where(id: params[:id]).where(user_id: current_user.id).take
              end

    respond_to do |format|
      if passkey
        passkey.destroy
        format.html { redirect_to passkeys_path, notice: 'Key was successfully destroyed.' }
      else
        format.html { redirect_to passkeys_path, alert: 'Key not found.' }
      end
    end
  end

  def password
    @passkey = Passkey.where(user_id: current_user.id).where(id: params[:id]).take
    if @passkey
      render json: { password: @passkey.password }
    else
      render json: { error: 'Not found' }, status: :not_found
    end
  end

  def search
    if params.dig(:search).length > 2
      search = "%#{params[:search]}%"
      @passkeys = Passkey.left_joins(:passkey_shares).where(
        "(passkeys.user_id = ? AND (title LIKE ? OR url LIKE ? OR tags LIKE ?))
       OR
         (passkey_shares.linked_user_id = ? AND (title LIKE ? OR url LIKE ? OR tags LIKE ?))",
        current_user.id, search, search, search, current_user.id, search, search, search
      ).order('updated_at desc')
      cookies[:search] = { value: params[:search], expires: 1.hour, httponly: true, secure: Rails.env.production? }
    else
      @passkeys = []
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('passkeys', partial: 'passkeys', locals: { passkeys: @passkeys })
        ]
      end
    end
  end

  private

  def add_version(passkey)
    # Create a copy for versions management.
    @passkey_version = PasskeyVersion.new(passkey_params.except('id', 'created_at', 'updated_at', 'picture'))
    @passkey_version.org_id = passkey.id
    @passkey_version.user_id = passkey.user_id
    @passkey_version.save
  end

  def set_passkey
    @passkey = Passkey.where(user_id: current_user.id).where(id: params[:id]).take
    redirect_to passkeys_url, alert: 'Key not found.' and return if @passkey.blank?
  end

  def passkey_params
    params.require(:passkey).permit(:title, :username, :password, :twofa, :url, :notes, :tags)
  end
end

app/views/passkeys/_form.html.erb
<%= form_with model: @passkey, id: "passkeyForm", class: "userinputs" do |form| %>
  <%= render "layouts/show_errors", resource: @passkey %>

  <div class="row">
    <div class="columns">
      <%= form.label :title, class: "label-th" %>
    </div>
    <div class="columns">
      <%= form.text_field :title, placeholder: "Enter title for this key" %>
    </div>
    <div class="columns">
      <%= form.label :username %>
    </div>
    <div class="columns">
      <%= form.text_field :username, placeholder: "Enter username" %>
    </div>
    <div class="columns small-6 medium-9">
      <%= form.label :password %>
      <%= form.text_field :password, id: 'passkey_password', placeholder: "Enter password" %>
    </div>
    <div class="columns small-4 medium-2 px-4">
      <label>New password</label>
      <span class="button tiny" data-action="click->passkey#newPassword">Generate</span>
    </div>
    <div class="columns small-2 medium-1">
      <%= form.label :twofa, id: "show2fa", class: @passkey.twofa? ? "icon xs star-filled filter-orange pb-2" : 'xs star-filled filter-orange pb-2icon pb-2' %>
      <%= form.label :twofa, class: "switch" do %>
        <%= form.check_box :twofa, id: 'passkey_twofa', data: { action: "click->passkey#set2fa" }, class: "switch" %>
        <span class="slider round"></span>
      <% end %>
    </div>
    <div class="columns">
      <%= form.label :url %>
    </div>
    <div class="columns">
      <%= form.text_field :url, placeholder: "New url" %>
    </div>
  </div>

  <!-- notes -->
  <div class="row">
    <div class="columns">
      <%= form.label :notes, class: "display-inline text-lg" %>
      <div id="preview_bt" data-action="click->passkey#showMarkdown" data-tooltip title="Click for preview" class="icon markdown align-bottom cursor-pointer"></div>
      <div id="edit_bt"    data-action="click->passkey#hideMarkdown" data-tooltip title="Click to edit"     class="icon edit align-bottom cursor-pointer display-none"></div>
      <%= form.text_area :notes, id: 'passkey_notes', placeholder: 'You can use markdown for Notes', rows: '20' %>
      <div id="markdown"></div>
    </div>
  </div>

  <!-- tags -->
  <div class="row">
    <div class="columns">
      <%= form.label :tags, class: "display-inline" %>
      <%= form.text_field :tags, id: 'passkey_tags', placeholder: 'Comma separeted values' %>
      <div id="tagsContainer"></div>
    </div>
  </div>
<% end %>

<%= render "shareDialog", resource: @passkey %>
<%= render "base/resource_footer", resource: @passkey %>

app/views/passkeys/_passkey_shares.html.erb
<div class="row">
  <div class="col-12">
   <%= content_tag :p, "Current shares", class: "color-bg-200 text-base py-2 pl-2" if @passkey_shares.any? %>
  </div>
  <% @passkey_shares.each do | share | %>
    <%= content_tag :div, share.email , class: "columns small-10 medium-10" %>
    <%= content_tag :div, class: "columns small-2 medium-2" do %>
      <%= link_to (content_tag :div, '', class: "icon delete filter"),
        passkey_share_path(id: share.id, passkey_id: share.passkey_id), data: { "turbo-method": :delete } %>
    <% end %>
  <% end %>
</div>

app/views/passkeys/_passkeys.html.erb
<div id="passkeys" class="col-12" data-turbo-prefetch="false">
<% @passkeys.each do |passkey| %>
  <%= link_to passkey_path(passkey), class: "row even p-2" do %>
  <div class="small-1 medium-1 columns">
    <%= content_tag :div, '', class: "icon star-filled filter-orange icon-top-pos" if passkey.twofa == 1 %>
  </div>
  <div class="small-10 medium-6 columns">
    <%= passkey.title %>
  </div>
  <div class="small-1 medium-2 columns">
    <%= content_tag :span, '', class: "icon share sm icon-top-pos", title: "Share passkey" unless passkey.user_id == current_user.id %>
    <%= content_tag :span, User.find(passkey.user_id).email, class: "hide-for-small-only" unless passkey.user_id == current_user.id %>
  </div>
  <div class="medium-1 columns hide-for-small-only whitespace-nowrap overflow-hidden">
    <%= content_tag :label, (passkey.user_id == current_user.id ? (l passkey.last_read, format: "%Y-%m-%d") : "Read only"), class: "button tiny display-inline" %>
  </div>
  <div class="medium-1 columns hide-for-small-only whitespace-nowrap overflow-hidden">
    <%= content_tag :label, (l passkey.updated_at, format: "%Y-%m-%d") %>
  </div>
  <div class="medium-1 columns hide-for-small-only whitespace-nowrap overflow-hidden">
    <%= content_tag :label, (l passkey.created_at, format: "%Y-%m-%d") %>
  </div>
  <% end %>
<% end %>
</div>

<%= content_tag :div, class: "row" do %>
  <div class="columns p-2">No passkeys yet, create one with the + icon.</div>
<% end unless @passkeys.any? %>

app/views/passkeys/_passkeyshares.html.erb
  <div class="row">
    <div class="columns">
     <p class="strong">Current shares</p>
    </div>
    <% @passkeyshares.each do | share | %>
      <%= content_tag :div, share.email , class: "columns small-10 medium-10" %>
      <%= content_tag :div, class: "columns small-2 medium-2" do %>
      <%= link_to passkeyshare_path(id: share.id, passkey_id: share.passkey_id), data: { "turbo-method": :delete } do %>
        <%= image_tag "delete.svg", class: "icon medium" %>
      <% end %>
    <% end %>
  <% end %>
  </div>

app/views/passkeys/_restore_menu.html.erb
<div class="row hide-for-print">
  <div class="columns medium-6" id="add-back-arrow">
    <h1 class="icon arrow-back cursor-pointer"></h1>
  </div>
  <div class="columns medium-6 text-right">
    <p><%= button_to "Restore version #{@passkey.id}", passkeyrestore_path,
      params: { version_id: @passkey.id} , class: "button warning" if @passkey.id %></p>
  </div>
</div>

app/views/passkeys/_secondary_menu.html.erb
<% unless @passkey.try(:org_id).present? || @passkey_readonly == true %>
<div class="row mb-6 hide-for-print">
  <div class="columns small-10 medium-10">
    <%= content_tag :div, '', class: "icon key p-2" unless @passkey.id %>
    <%= link_to (content_tag :div, '', class: "icon key pr-2 border-right-dashed"),
      passkey_path(@passkey), title: "Back to passkey without saving" if @passkey.id %>

    <%= link_to (content_tag :div, '', class: "icon edit p-2 border-right-dashed"),
      edit_passkey_path(@passkey), title: "Edit passkey" if action_name == "show" %>

    <%= link_to (content_tag :div, '', class: "icon visibility p-2 border-right-dashed"),
      passkey_path(@passkey), title: "Show passkey" if action_name == "edit" %>

    <%= content_tag :div, '', class: "icon cloud-upload p-2 cursor-pointer", id: "cloud-upload",
      data: { action: "click->passkey#submitForm" }, title: "Save passkey" if action_name != "show" %>

    <%= link_to (content_tag :div, '', class: "icon restore p-2 border-right-dashed"),
      passkey_versions_path(org_id: @passkey.id), title: "Versions of this passkey" if @passkey.id %>

    <%= content_tag :div, '', class: "icon share p-2 cursor-pointer", id: "share", title: "Share passkey",
      data: { controller: "passkey", action: "click->passkey#openShareDialog" } if @passkey.id %>

  </div>
  <div class="columns small-2 medium-2 text-right">
    <%= link_to (content_tag :div, '', class: "icon delete p-2"),
      passkey_path(@passkey), data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete this passkey?'},
      title: "Delete item!" if @passkey.id %>
  </div>
</div>
<% end %>

app/views/passkeys/_shareDialog.html.erb
<dialog id="shareDialog" class="dialog" data-controller="passkey">
  <div class="row color-900 text-xl py-2">
    <div class="columns small-10 medium-11">Share this key</div>
    <div class="columns small-2 medium-1 text-right">
      <span class="close" data-action="click->passkey#closeShareDialog">&times;</span>
    </div>
  </div>
  <div id="dialog_flash">
    <%= render "layouts/dialog_flash" if @passkey_shares %>
  </div>
  <div id="passkey_sharesForm">
    <%= render "passkeys/passkey_shares" if @passkey_shares %>
  </div>
  <div class="row">
    <div class="columns">
      <%= form_with url: passkey_shares_path, model: @passkey_share do |form| %>
        <%= form.hidden_field :passkey_id %>

        <%= label_tag :email, "Emailaddress" %>
        <%= form.email_field :email, placeholder: "Add other emailaddress to share with" %>

        <p><%= form.submit "Save", class: "button" %></p>
      <% end if @passkey_shares %>
    </div>
  </div>
</dialog>

app/views/passkeys/edit.html.erb
<div data-controller="passkey">
  <%= render "secondary_menu" %>
  <%= render "form", passkey: @passkey %>
</div>

app/views/passkeys/index.html.erb
<div class="row mb-6">
  <div class="small-10 medium-10 columns">
    <div class="icon lock p-2 border-right-dashed"></div>
    <%= link_to (content_tag :div, '', class: "icon share p-2 border-right-dashed"),
       passkey_shares_path, title: "Show passkey shares", date: { tooltip: ''} %>
     <div class="icon search p-2 cursor-pointer" data-controller="passkey"
       data-action="click->passkey#showSearch" title="Search keys"></div>
  </div>
  <div class="small-2 medium-2 columns text-right">
    <%= link_to (content_tag :div, '', class: "icon add p-2"),
      new_passkey_path, data: { turbo_frame: dom_id(Passkey.new) }, title: "Add key" %>
  </div>
</div>

<div id="show_search" class="row display-none">
  <div class="columns">
  <%= form_with url: passkeys_search_path, id: "search-form" do |form| %>
    <%= form.search_field :search, id: 'search', placeholder: 'Search passkeys', value: cookies[:search],
      data: { controller: "passkey", action: "focus->passkey#search input->passkey#search" } %>
  <% end %>
  </div>
</div>

<div class="row color-bg-300 p-2">
  <div class="medium-1 columns hide-for-small-only">2FA</div>
  <div class="medium-6 columns">Keys</div>
  <div class="medium-2 columns hide-for-small-only">Shared by</div>
  <div class="medium-1 columns hide-for-small-only">Last read</div>
  <div class="medium-1 columns hide-for-small-only">Updated</div>
  <div class="medium-1 columns hide-for-small-only">Created</div>
</div>
<%= render "passkeys" %>

app/views/passkeys/new.html.erb
<div data-controller="passkey">
  <%= render "secondary_menu" %>
  <%= render "form", passkey: @passkey %>
</div>

app/views/passkeys/show.html.erb
<%= render "passkeys/secondary_menu" %>
<%= render "passkeys/restore_menu" if @passkey.try(:org_id) %>

<div class="row" data-controller="passkey">
  <div class="columns medium-6">
    <div class="row">
      <div class="columns">
        <h2><%= @passkey.title %></h2>
      </div>
      <div class="columns">
        <%= label_tag :username, nil, class: "text-lg" %>
      </div>
      <div class="columns small-10 medium-11 mb-6">
        <%= content_tag :div, @passkey.username, id: "username" %>
      </div>
      <div class="columns small-2 medium-1">
        <div data-action="click->passkey#copyUsername" data-passkey-target="copiedUsername" class="icon copy"></div>
      </div>
      <div class="columns <%= "icon xs star-filled filter-orange" if @passkey.twofa == 1 %>">
        <%= label_tag :password, nil, class: "text-lg display-inline" %>
        <%= content_tag :div, '', class: "icon visibility label filter", id: "passwordToggle",
          data: { "action": "click->passkey#togglePassword" } %>
      </div>
      <div class="columns small-10 medium-11 mb-6">
        <%= password_field_tag 'password', nil, placeholder: 'Click copy to load',
          data: { "passkey_target": "passwordToggle", "passkey_id": @passkey.id, "action": "click->passkey#togglePassword" }  %>
      </div>
      <div class="columns small-2 medium-1">
        <div data-action="click->passkey#copyPassword" data-passkey-target="copiedPassword" data-passkey-id="<%= @passkey.id %>" class="icon copy"></div>
      </div>
      <div class="columns mb-6">
        <%= label_tag :url, nil, class: "text-lg" %>
        <%= link_to @passkey.url, @passkey.url, target: "_blank" %>
      </div>
    </div>
  </div>
  <div class="columns medium-6">
    <div id="passkey_shares">
     <%= render "passkey_shares", resource: @passkey_shares unless @passkey_readonly || @passkey_shares && @passkey_shares.none?%>
    </div>
  </div>
</div>

<%= content_tag :div, class: "row", data: { controller: "passkey" } do %>
  <div class="columns">
    <%= label_tag :notes, nil, class:"text-lg display-inline" %>
    <%= content_tag :div, '', class: "icon visibility label", id: "notesToggle", data: { "action": "click->passkey#toggleNotes" } %>
    <%= content_tag :pre, @passkey.notes, id: "notes", class: "display-none" %>
    <div id="markdown" class="callout hide-notes disabled" data-passkey-target="notesToggle">Click to show notes</div>
  </div>
<% end if @passkey.notes.present? %>

<div class="row">
  <div class="columns hide-for-print">
    <%= content_tag :div, '', id: "tagsContainer" if @passkey.tags.present? %>
    <%= hidden_field_tag "passkey_tags", @passkey.tags %>
  </div>
</div>

<%= render "/passkeys/shareDialog", resource: @passkey if @passkey_shares %>
<%= render "base/resource_footer", resource: @passkey %>