config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated  do
    root "base#index", as: 'unauthenticated_user'
  end
  unauthenticated do
    root "base#about"
  end

  get "about", to: "base#about"
  get "welcome", to: "base#welcome"
  post "offline_data", to: "base#update_offline_data"

  get "events/drag", to: "events#drag"
  post "events/search", to: "events#search"
  post "eventrestore", to: "event_versions#restore", as: "eventrestore"
  get "event_versions/compare", to: "event_versions#compare"

  post "contactrestore", to: "contact_versions#restore", as: "contactrestore"
  post "contacts/search", to: "contacts#search"
  get "contact_versions/compare", to: "contact_versions#compare"

  post "postrestore", to: "post_versions#restore", as: "postrestore"
  post "posts/search", to: "posts#search"
  delete "post/image", to: "posts#destroy_image"
  get "post_versions/compare", to: "post_versions#compare"

  post "passkeyrestore", to: "passkey_versions#restore", as: "passkeyrestore"
  post "passkeys/search", to: "passkeys#search"
  get "passkeys/:id/password", to: "passkeys#password", as: "passkey_password"
  get "passkey_versions/compare", to: "passkey_versions#compare"

  resources :events
  resources :event_versions
  resources :contacts
  resources :contact_versions
  resources :posts
  resources :post_versions
  resources :passkeys
  resources :passkey_versions
  resources :passkey_shares

end

app/models/post.rb
class Post < ApplicationRecord

  attr_accessor :file

  self.inheritance_column = 'zoink'
  alias_attribute :category, :type
  alias_attribute :notes, :content
  alias_attribute :created_at, :created
  alias_attribute :updated_at, :updated

  validates :title, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy destroy_image]

  def index
    @posts = Post.where(user_id: current_user.id).order('last_read desc').limit 500

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post.update_column(:last_read, DateTime.now)
    get_files
  end

  def new
    @post = Post.new
  end

  def edit
    get_files
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('postForm', partial: 'posts/form', locals: { resource: @post })
        end
      end
    end

    # Create a copy for versions management.
    add_version(@post)
  end

  def update
    uploaded_file = params[:post][:file] if params[:post].present?
    if uploaded_file.present?
      path = "#{Rails.root}/public/uploads/#{current_user.id}/posts/#{@post.id}"
      FileUtils.mkdir_p(path) unless Dir.exist?(path)
      File.open(Rails.root.join('public', 'uploads', current_user.id.to_s, 'posts', @post.id.to_s, sanitize_filename(uploaded_file.original_filename)), 'wb') do |file|
        file.write(uploaded_file.read)
      end
    end

    respond_to do |format|
      if @post.update(post_params)
        if uploaded_file
          format.turbo_stream do
            get_files
            render turbo_stream: turbo_stream.update('images', partial: 'posts/images', locals: { resource: @post })
          end
        end
        unless uploaded_file
          format.html do
            redirect_to post_url(@post), notice: 'Post was successfully updated.'
          end
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('postForm', partial: 'posts/form', locals: { resource: @post })
        end
      end
    end

    # Create a copy for versions management.
    add_version(@post)
  end

  def destroy
    @post.destroy
    dir = "#{Rails.root}/public/uploads/#{current_user.id}/posts/#{@post.id}/"
    FileUtils.rm_rf(dir)
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_image
    filename = sanitize_filename(params[:file])
    img = "#{Rails.root}/public/uploads/#{current_user.id}/posts/#{@post.id}/#{filename}"
    File.delete(img) if File.exist?(img)
    get_files
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('images', partial: 'posts/images', locals: { resource: @post })
      end
    end
  end

  def search
    if params.dig(:search).length > 2
      search = "%#{params[:search]}%"
      @posts = Post.where('title LIKE ? OR content LIKE ? OR tags LIKE ?', search, search, search)
                   .order(updated_at: :desc).where(user_id: current_user.id)
      cookies[:search] = { value: params[:search], expires: 1.hour, httponly: true, secure: Rails.env.production? }
    else
      @posts = []
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('posts', partial: 'posts', locals: { posts: @posts })
        ]
      end
    end
  end

  private

  def add_version(post)
    # Create a copy for versions management.
    @post_version = PostVersion.new(post_params.except('id', 'created_at', 'updated_at', 'file'))
    @post_version.org_id = post.id
    @post_version.user_id = post.user_id
    @post_version.save
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.where(user_id: current_user.id).where(id: params[:id]).take
  end

  def get_files
    path = "storage/#{current_user.id}/posts/#{@post.id}"
    FileUtils.mkdir_p(path) unless Dir.exist?(path)
    @files = Dir.children(path)
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :notes, :file, :category, :tags)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, id: "postForm", class: "userinputs", data: { controller: "post" } do |form| %>
  <%= render "layouts/show_errors", resource: @post %>

  <div class="row">
    <div class="columns">
      <%= form.text_field :title, placeholder: "Note title" %>
    </div>
  </div>

  <!-- notes -->
  <div class="row">
    <div class="columns">
      <div class="icon markdown align-bottom" id="preview_bt" data-action="click->post#showMarkdown" data-tooltip title="Click for markdown preview"></div>
      <div class="icon edit align-bottom display-none" id="edit_bt" data-action="click->post#hideMarkdown" data-tooltip title="Click to edit"></div>
      <%= form.label :notes, class: "text-lg display-inline" %>
      <%= form.text_area :notes, id: 'post_notes', placeholder: 'You can use markdown for notes', rows: '30' %>
      <div id="markdown"></div>
    </div>
  </div>

  <div class="row">
    <div class="medium-6 columns">
    <fieldset>
      <legend class="strong">Category</legend>
      <div class="row p-4">
        <div class="column small-6 medium-6">Post</div>
        <div class="column small-6 medium-6 post">
        <%= form.label :category_post, class: "switch" do %>
          <%= form.radio_button :category, "post", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Hobby</div>
        <div class="column small-6 medium-6 hobby">
        <%= form.label :category_hobby, class: "switch" do %>
          <%= form.radio_button :category, "hobby", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Memo</div>
        <div class="column small-6 medium-6 memo">
        <%= form.label :category_memo, class: "switch" do %>
          <%= form.radio_button :category, "memo", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Task</div>
        <div class="column small-6 medium-6 task">
        <%= form.label :category_task, class: "switch" do %>
          <%= form.radio_button :category, "task", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Business</div>
        <div class="column small-6 medium-6 business">
        <%= form.label :category_business, class: "switch" do %>
          <%= form.radio_button :category, "business", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
      <div class="row p-4">
        <div class="column small-6 medium-6">Holiday</div>
        <div class="column small-6 medium-6 holiday">
        <%= form.label :category_holiday, class: "switch" do %>
          <%= form.radio_button :category, "holiday", class: "switch" %>
          <span class="slider round"></span>
        <% end %>
        </div>
      </div>
    </fieldset>
    </div>

    <div class="columns medium-6">
    <fieldset>
      <p><legend class="strong">Tags</legend></p>
      <%= form.text_field :tags, id: 'post_tags', placeholder: 'Comma separeted values' %>
      <div id="tagsContainer"></div>
    </fieldset>
    </div>
  </div>

<% end %>

<%= render "base/resource_footer", resource: @post %>

app/views/posts/_images.html.erb
<% @files.each do |file| %>
  <div class="row even my-4">
    <div class="medium-6 columns pt-8">
      <%= file %>
    </div>
    <div class="medium-2 columns">
      <% if file.match? /.jpg$|.jpeg$|.gif$|.png$/ %>
        <%= image_tag "/uploads/#{current_user.id}/posts/#{@post.id}/#{file}" %>
      <% elsif file.match? /.pdf$/ %>
        <%= content_tag :div, '', class: 'icon pdf xl4', style: 'height: 100%' %>
      <% else %>
        <%= content_tag :div, '', class: 'icon unknown-document xl4', style: 'height: 100%' %>
      <% end %>
    </div>
    <div class="medium-4 columns pt-8">
      <%= content_tag :div, "Copy link", id: "#{file}", title: "/uploads/#{current_user.id}/posts/#{@post.id}/#{file}",
     data: { controller: "post", "action": "click->post#copyImageUrl" }, class: "button tiny" %>
      <%= link_to '', post_image_path(id: @post.id, file: file),
      data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete this image?'},
      class: "icon delete float-right" %>
    </div>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div id="posts" data-turbo-prefetch="false">
<% @posts.each do |post| %>
  <%= link_to post_path(post), class: "row p-2 even #{post.category}" do %>
  <div class="medium-6 columns">
    <%= post.title %>
  </div>
  <div class="medium-2 columns hide-for-small-only">
    <%= content_tag :label, (l post.last_read, format: "%Y-%m-%d"), class: "button tiny" %>
  </div>
  <div class="medium-2 columns hide-for-small-only">
    <%= content_tag :label, (l post.updated_at, format: "%Y-%m-%d") %>
  </div>
  <div class="medium-2 columns hide-for-small-only">
    <%= content_tag :label, (l post.created_at, format: "%Y-%m-%d") %>
  </div>
  <% end %>
<% end %>
</div>

<%= content_tag :div, class: "row" do %>
  <div class="columns p-2">No notes yet, create one with the + icon.</div>
<% end unless @posts.any? %>

app/views/posts/_restore_menu.html.erb
<div class="row hide-for-print">
  <div class="columns medium-6" id="add-back-arrow">
    <h1 class="icon arrow-back cursor-pointer"></h1>
  </div>
  <div class="columns medium-6 text-right">
    <p><%= button_to "Restore version #{@post.id}", postrestore_path,
      params: { version_id: @post.id} , class: "button warning" if @post.id %></p>
  </div>
</div>

app/views/posts/_secondary_menu.html.erb
<div class="row mb-6 hide-for-print">
  <div class="columns small-10 medium-10">
    <%= content_tag :div, '', class: "icon article p-2 cursor-pointer border-right-dashed" unless @post.id %>
    <%= link_to (content_tag :div, '', class: "icon article p-2 border-right-dashed"),
      post_path(@post), title: "Back to post, without saving" if @post.id %>

    <%= link_to (content_tag :div, '', class: "icon edit p-2 border-right-dashed"),
      edit_post_path(@post), title: "Edit post" if action_name == "show" %>

    <%= content_tag :div, '', class: "icon cloud-upload p-2 cursor-pointer border-right-dashed", id: "cloud-upload",
      data: { action: "click->post#submitForm" }, title: "Save post" if action_name != "show" %>

    <%= content_tag :div, @files.length, class: "icon image-add p-2 cursor-pointer border-right-dashed",
      data: { modal_open: "addFile" } if @post.id && action_name == "edit" %>

    <%= link_to (content_tag :div, '', class: "icon restore p-2"),
      post_versions_path(org_id: @post.id), title: "Versions of this post" if @post.id %>

  </div>
  <div class="columns small-2 medium-2 text-right">
    <%= link_to (content_tag :div, '', class: "icon delete p-2"), post_path(@post),
      data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete this post?'},
      title: "Delete note" if @post.id %>
  </div>
</div>

app/views/posts/edit.html.erb
<div data-controller="post">
  <%= render "secondary_menu" %>
  <%= render "form", post: @post %>
</div>

<div class="modal" id="addFile">
  <%= form_with model: @post, id: "postForm" do |form| %>
  <div class="modal-content">

    <div class="row color-bg-100 mb-4">
      <div class="columns py-2">
        <span class="close-button pt-2" data-modal-close="addFile">&#215;</span>
        <strong>Upload new file</strong>
        <p>After uploading a file you can copy the link and past it anyware into the note with markdown.</p>
      </div>
    </div>
    <div class="row my-4">
      <div class="columns">
        <%= form.file_field :file %>
        <%= form.submit "Upload", class: "button" %>
      </div>
    </div>

    <%= content_tag :div, class:"row color-bg-100 my-4" do %>
      <%= content_tag :div, "Select copy size", class:"columns small-6 medium-8 text-lg p-1 my-2" %>
      <div class="columns small-6 medium-4 text-xs">
        <%= select_tag "image_size", options_for_select(
          {"Image size 100" => "img-100",
           "Image size 200" => "img-200",
           "Image size 300" => "img-300",
           "Image size 400" => "img-400",
           "Image size 500" => "img-500",
           "Image size 600" => "img-600",
           "Image size 700" => "img-700",
           "Image size 800" => "img-800" }, "img-400"),
          style: "margin: 5px; font-size: small" %>
      </div>
    <% end %>

    <div id="images">
      <%= render "images" %>
    </div>

  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="row mb-6">
  <div class="small-10 medium-10 columns">
    <div class="icon article p-2 border-right-dashed"></div>
    <div class="icon search p-2 cursor-pointer" data-controller="post" data-action="click->post#showSearch" title="Search notes"></div>
  </div>
  <div class="small-2 medium-2 columns text-right">
    <%= link_to (content_tag :div, '', class: "icon add p-2"),
      new_post_path, data: { turbo_frame: dom_id(Post.new) }, title: "Add post" %>
  </div>
</div>

<div id="show_search" class="row display-none">
  <div class="columns">
  <%= form_with url: posts_search_path, id: "search-form" do |form| %>
    <%= form.search_field :search, id: 'search', placeholder: 'Search notes', value: cookies[:search],
      data: { controller: "post", action: "focus->post#search input->post#search" } %>
  <% end %>
  </div>
</div>

<div class="row p-2 color-bg-300">
  <div class="medium-6 columns">Notes</div>
  <div class="medium-2 columns hide-for-small-only ">Last read</div>
  <div class="medium-2 columns hide-for-small-only ">Updated</div>
  <div class="medium-2 columns hide-for-small-only ">Created</div>
</div>
<%= render "posts" %>

app/views/posts/new.html.erb
<div data-controller="post">
  <%= render "secondary_menu" %>
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<%= render "posts/secondary_menu" unless @post.try(:org_id) %>
<%= render "posts/restore_menu" if @post.try(:org_id) %>

<%= form_with model: @post do |form| %>
<div class="row">
  <div class="columns <%= @post.category %>">
    <h2><%= @post.title %></h2>
  </div>
</div>

<div class="row">
  <div class="columns">
    <%= text_area_tag :notes, @post.notes, class: "display-none" %>
    <fieldset id="tocFieldset">
      <legend>Content</legend>
      <div id="toc"></div>
    </fieldset>
    <div data-controller="post" id="markdown"></div>
  </div>
</div>

<div class="row hide-for-print">
  <div class="columns">
    <%= content_tag :div, '', id: "tagsContainer" if @post.tags.present? %>
    <%= hidden_field_tag "post_tags", @post.tags %>
  </div>
</div>
<% end %>

<%= render "base/resource_footer", resource: @post %>